import { describe, expect, it } from 'vitest';
import { normalizeOutlineEnvelope } from '@/lib/generation/outline-envelope-normalization';
import { convergeCourseInputOutlines } from '@/lib/generation/orchestration/input-outline-convergence';
import { makeHighQualityOutlines } from './course-quality-fixtures';
import type { SceneOutline } from '@/lib/types/generation';

describe('outline envelope normalization', () => {
  it('unwraps a nested provider envelope embedded as the first array item', () => {
    const scenes = makeHighQualityOutlines();
    const malformed = [
      {
        courseTitle: 'Architecture course',
        languageDirective: 'Teach in Chinese.',
        outlines: [...scenes.slice(0, 4), 'languageNote', ':', 'Chinese'],
      },
      ...scenes.slice(4),
    ];

    const normalized = normalizeOutlineEnvelope(malformed);

    expect(normalized?.courseTitle).toBe('Architecture course');
    expect(normalized?.languageDirective).toBe('Teach in Chinese.');
    expect(normalized?.outlines).toHaveLength(scenes.length);
    expect(normalized?.outlines.map((scene) => scene.title)).toEqual(
      scenes.map((scene) => scene.title),
    );
  });

  it('unwraps stale browser input again at the durable job boundary', () => {
    const scenes = makeHighQualityOutlines();
    const stale = [
      {
        id: 'wrapper',
        type: 'slide',
        order: 1,
        title: 'Scene 1: an entire user requirement that must not become a classroom page',
        description: 'Synthetic wrapper generated by an older streaming parser.',
        keyPoints: ['Synthetic wrapper', 'Not learner content', 'Must be unwrapped'],
        outlines: scenes.slice(0, 4),
      },
      ...scenes.slice(4),
    ] as unknown as SceneOutline[];

    const converged = convergeCourseInputOutlines(stale);

    expect(converged.outlines).toHaveLength(scenes.length);
    expect(converged.outlines.some((scene) => 'outlines' in scene)).toBe(false);
    expect(converged.outlines[0].title).toBe(scenes[0].title);
    expect(converged.assessment.passed, JSON.stringify(converged.assessment, null, 2)).toBe(true);
  });
});
